#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSTERIAPPS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Musteri")]
	public partial class MusteriDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKimlik(Kimlik instance);
    partial void UpdateKimlik(Kimlik instance);
    partial void DeleteKimlik(Kimlik instance);
    partial void InsertUrunlerSil(UrunlerSil instance);
    partial void UpdateUrunlerSil(UrunlerSil instance);
    partial void DeleteUrunlerSil(UrunlerSil instance);
    partial void InsertKimlikSil(KimlikSil instance);
    partial void UpdateKimlikSil(KimlikSil instance);
    partial void DeleteKimlikSil(KimlikSil instance);
    partial void InsertKullanici(Kullanici instance);
    partial void UpdateKullanici(Kullanici instance);
    partial void DeleteKullanici(Kullanici instance);
    partial void InsertSatislar(Satislar instance);
    partial void UpdateSatislar(Satislar instance);
    partial void DeleteSatislar(Satislar instance);
    partial void InsertSatislarSil(SatislarSil instance);
    partial void UpdateSatislarSil(SatislarSil instance);
    partial void DeleteSatislarSil(SatislarSil instance);
    partial void InsertStokHareket(StokHareket instance);
    partial void UpdateStokHareket(StokHareket instance);
    partial void DeleteStokHareket(StokHareket instance);
    partial void InsertStokHareketSil(StokHareketSil instance);
    partial void UpdateStokHareketSil(StokHareketSil instance);
    partial void DeleteStokHareketSil(StokHareketSil instance);
    partial void InsertUrunler(Urunler instance);
    partial void UpdateUrunler(Urunler instance);
    partial void DeleteUrunler(Urunler instance);
    #endregion
		
		public MusteriDataDataContext() : 
				base(global::MUSTERIAPPS.Properties.Settings.Default.MusteriConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kimlik> Kimliks
		{
			get
			{
				return this.GetTable<Kimlik>();
			}
		}
		
		public System.Data.Linq.Table<UrunlerSil> UrunlerSils
		{
			get
			{
				return this.GetTable<UrunlerSil>();
			}
		}
		
		public System.Data.Linq.Table<KimlikSil> KimlikSils
		{
			get
			{
				return this.GetTable<KimlikSil>();
			}
		}
		
		public System.Data.Linq.Table<Kullanici> Kullanicis
		{
			get
			{
				return this.GetTable<Kullanici>();
			}
		}
		
		public System.Data.Linq.Table<Odeme> Odemes
		{
			get
			{
				return this.GetTable<Odeme>();
			}
		}
		
		public System.Data.Linq.Table<Satislar> Satislars
		{
			get
			{
				return this.GetTable<Satislar>();
			}
		}
		
		public System.Data.Linq.Table<SatislarSil> SatislarSils
		{
			get
			{
				return this.GetTable<SatislarSil>();
			}
		}
		
		public System.Data.Linq.Table<StokHareket> StokHarekets
		{
			get
			{
				return this.GetTable<StokHareket>();
			}
		}
		
		public System.Data.Linq.Table<StokHareketSil> StokHareketSils
		{
			get
			{
				return this.GetTable<StokHareketSil>();
			}
		}
		
		public System.Data.Linq.Table<Urunler> Urunlers
		{
			get
			{
				return this.GetTable<Urunler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kimlik")]
	public partial class Kimlik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MusteriId;
		
		private string _MusteriNo;
		
		private string _FirmaBilgisi;
		
		private string _YetkiliAdi;
		
		private string _YetkiliSoyadi;
		
		private string _FirmaAdresi;
		
		private string _TelefonNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIdChanging(int value);
    partial void OnMusteriIdChanged();
    partial void OnMusteriNoChanging(string value);
    partial void OnMusteriNoChanged();
    partial void OnFirmaBilgisiChanging(string value);
    partial void OnFirmaBilgisiChanged();
    partial void OnYetkiliAdiChanging(string value);
    partial void OnYetkiliAdiChanged();
    partial void OnYetkiliSoyadiChanging(string value);
    partial void OnYetkiliSoyadiChanged();
    partial void OnFirmaAdresiChanging(string value);
    partial void OnFirmaAdresiChanged();
    partial void OnTelefonNoChanging(string value);
    partial void OnTelefonNoChanged();
    #endregion
		
		public Kimlik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MusteriId
		{
			get
			{
				return this._MusteriId;
			}
			set
			{
				if ((this._MusteriId != value))
				{
					this.OnMusteriIdChanging(value);
					this.SendPropertyChanging();
					this._MusteriId = value;
					this.SendPropertyChanged("MusteriId");
					this.OnMusteriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriNo", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string MusteriNo
		{
			get
			{
				return this._MusteriNo;
			}
			set
			{
				if ((this._MusteriNo != value))
				{
					this.OnMusteriNoChanging(value);
					this.SendPropertyChanging();
					this._MusteriNo = value;
					this.SendPropertyChanged("MusteriNo");
					this.OnMusteriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaBilgisi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirmaBilgisi
		{
			get
			{
				return this._FirmaBilgisi;
			}
			set
			{
				if ((this._FirmaBilgisi != value))
				{
					this.OnFirmaBilgisiChanging(value);
					this.SendPropertyChanging();
					this._FirmaBilgisi = value;
					this.SendPropertyChanged("FirmaBilgisi");
					this.OnFirmaBilgisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliAdi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string YetkiliAdi
		{
			get
			{
				return this._YetkiliAdi;
			}
			set
			{
				if ((this._YetkiliAdi != value))
				{
					this.OnYetkiliAdiChanging(value);
					this.SendPropertyChanging();
					this._YetkiliAdi = value;
					this.SendPropertyChanged("YetkiliAdi");
					this.OnYetkiliAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliSoyadi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string YetkiliSoyadi
		{
			get
			{
				return this._YetkiliSoyadi;
			}
			set
			{
				if ((this._YetkiliSoyadi != value))
				{
					this.OnYetkiliSoyadiChanging(value);
					this.SendPropertyChanging();
					this._YetkiliSoyadi = value;
					this.SendPropertyChanged("YetkiliSoyadi");
					this.OnYetkiliSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdresi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirmaAdresi
		{
			get
			{
				return this._FirmaAdresi;
			}
			set
			{
				if ((this._FirmaAdresi != value))
				{
					this.OnFirmaAdresiChanging(value);
					this.SendPropertyChanging();
					this._FirmaAdresi = value;
					this.SendPropertyChanged("FirmaAdresi");
					this.OnFirmaAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonNo", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string TelefonNo
		{
			get
			{
				return this._TelefonNo;
			}
			set
			{
				if ((this._TelefonNo != value))
				{
					this.OnTelefonNoChanging(value);
					this.SendPropertyChanging();
					this._TelefonNo = value;
					this.SendPropertyChanged("TelefonNo");
					this.OnTelefonNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UrunlerSil")]
	public partial class UrunlerSil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UrunId;
		
		private string _UrunKodu;
		
		private string _UrunTanimi;
		
		private int _UrunMiktari;
		
		private decimal _AlisFiyati;
		
		private decimal _SatisFiyati;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIdChanging(int value);
    partial void OnUrunIdChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnUrunTanimiChanging(string value);
    partial void OnUrunTanimiChanged();
    partial void OnUrunMiktariChanging(int value);
    partial void OnUrunMiktariChanged();
    partial void OnAlisFiyatiChanging(decimal value);
    partial void OnAlisFiyatiChanged();
    partial void OnSatisFiyatiChanging(decimal value);
    partial void OnSatisFiyatiChanged();
    #endregion
		
		public UrunlerSil()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UrunId
		{
			get
			{
				return this._UrunId;
			}
			set
			{
				if ((this._UrunId != value))
				{
					this.OnUrunIdChanging(value);
					this.SendPropertyChanging();
					this._UrunId = value;
					this.SendPropertyChanged("UrunId");
					this.OnUrunIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTanimi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UrunTanimi
		{
			get
			{
				return this._UrunTanimi;
			}
			set
			{
				if ((this._UrunTanimi != value))
				{
					this.OnUrunTanimiChanging(value);
					this.SendPropertyChanging();
					this._UrunTanimi = value;
					this.SendPropertyChanged("UrunTanimi");
					this.OnUrunTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunMiktari", DbType="Int NOT NULL")]
		public int UrunMiktari
		{
			get
			{
				return this._UrunMiktari;
			}
			set
			{
				if ((this._UrunMiktari != value))
				{
					this.OnUrunMiktariChanging(value);
					this.SendPropertyChanging();
					this._UrunMiktari = value;
					this.SendPropertyChanged("UrunMiktari");
					this.OnUrunMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlisFiyati", DbType="Money NOT NULL")]
		public decimal AlisFiyati
		{
			get
			{
				return this._AlisFiyati;
			}
			set
			{
				if ((this._AlisFiyati != value))
				{
					this.OnAlisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._AlisFiyati = value;
					this.SendPropertyChanged("AlisFiyati");
					this.OnAlisFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisFiyati", DbType="Money NOT NULL")]
		public decimal SatisFiyati
		{
			get
			{
				return this._SatisFiyati;
			}
			set
			{
				if ((this._SatisFiyati != value))
				{
					this.OnSatisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._SatisFiyati = value;
					this.SendPropertyChanged("SatisFiyati");
					this.OnSatisFiyatiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KimlikSil")]
	public partial class KimlikSil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MusteriId;
		
		private string _MusteriNo;
		
		private string _FirmaBilgisi;
		
		private string _YetkiliAdi;
		
		private string _YetkiliSoyadi;
		
		private string _FirmaAdresi;
		
		private string _TelefonNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIdChanging(int value);
    partial void OnMusteriIdChanged();
    partial void OnMusteriNoChanging(string value);
    partial void OnMusteriNoChanged();
    partial void OnFirmaBilgisiChanging(string value);
    partial void OnFirmaBilgisiChanged();
    partial void OnYetkiliAdiChanging(string value);
    partial void OnYetkiliAdiChanged();
    partial void OnYetkiliSoyadiChanging(string value);
    partial void OnYetkiliSoyadiChanged();
    partial void OnFirmaAdresiChanging(string value);
    partial void OnFirmaAdresiChanged();
    partial void OnTelefonNoChanging(string value);
    partial void OnTelefonNoChanged();
    #endregion
		
		public KimlikSil()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MusteriId
		{
			get
			{
				return this._MusteriId;
			}
			set
			{
				if ((this._MusteriId != value))
				{
					this.OnMusteriIdChanging(value);
					this.SendPropertyChanging();
					this._MusteriId = value;
					this.SendPropertyChanged("MusteriId");
					this.OnMusteriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriNo", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string MusteriNo
		{
			get
			{
				return this._MusteriNo;
			}
			set
			{
				if ((this._MusteriNo != value))
				{
					this.OnMusteriNoChanging(value);
					this.SendPropertyChanging();
					this._MusteriNo = value;
					this.SendPropertyChanged("MusteriNo");
					this.OnMusteriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaBilgisi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirmaBilgisi
		{
			get
			{
				return this._FirmaBilgisi;
			}
			set
			{
				if ((this._FirmaBilgisi != value))
				{
					this.OnFirmaBilgisiChanging(value);
					this.SendPropertyChanging();
					this._FirmaBilgisi = value;
					this.SendPropertyChanged("FirmaBilgisi");
					this.OnFirmaBilgisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliAdi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string YetkiliAdi
		{
			get
			{
				return this._YetkiliAdi;
			}
			set
			{
				if ((this._YetkiliAdi != value))
				{
					this.OnYetkiliAdiChanging(value);
					this.SendPropertyChanging();
					this._YetkiliAdi = value;
					this.SendPropertyChanged("YetkiliAdi");
					this.OnYetkiliAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliSoyadi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string YetkiliSoyadi
		{
			get
			{
				return this._YetkiliSoyadi;
			}
			set
			{
				if ((this._YetkiliSoyadi != value))
				{
					this.OnYetkiliSoyadiChanging(value);
					this.SendPropertyChanging();
					this._YetkiliSoyadi = value;
					this.SendPropertyChanged("YetkiliSoyadi");
					this.OnYetkiliSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdresi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirmaAdresi
		{
			get
			{
				return this._FirmaAdresi;
			}
			set
			{
				if ((this._FirmaAdresi != value))
				{
					this.OnFirmaAdresiChanging(value);
					this.SendPropertyChanging();
					this._FirmaAdresi = value;
					this.SendPropertyChanged("FirmaAdresi");
					this.OnFirmaAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonNo", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string TelefonNo
		{
			get
			{
				return this._TelefonNo;
			}
			set
			{
				if ((this._TelefonNo != value))
				{
					this.OnTelefonNoChanging(value);
					this.SendPropertyChanging();
					this._TelefonNo = value;
					this.SendPropertyChanged("TelefonNo");
					this.OnTelefonNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanici")]
	public partial class Kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KullaniciId;
		
		private string _KullaniciAdi;
		
		private string _KullaniciSifresi;
		
		private string _KullaniciYetkisi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKullaniciIdChanging(int value);
    partial void OnKullaniciIdChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnKullaniciSifresiChanging(string value);
    partial void OnKullaniciSifresiChanged();
    partial void OnKullaniciYetkisiChanging(string value);
    partial void OnKullaniciYetkisiChanged();
    #endregion
		
		public Kullanici()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KullaniciId
		{
			get
			{
				return this._KullaniciId;
			}
			set
			{
				if ((this._KullaniciId != value))
				{
					this.OnKullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._KullaniciId = value;
					this.SendPropertyChanged("KullaniciId");
					this.OnKullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciSifresi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KullaniciSifresi
		{
			get
			{
				return this._KullaniciSifresi;
			}
			set
			{
				if ((this._KullaniciSifresi != value))
				{
					this.OnKullaniciSifresiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciSifresi = value;
					this.SendPropertyChanged("KullaniciSifresi");
					this.OnKullaniciSifresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciYetkisi", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string KullaniciYetkisi
		{
			get
			{
				return this._KullaniciYetkisi;
			}
			set
			{
				if ((this._KullaniciYetkisi != value))
				{
					this.OnKullaniciYetkisiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciYetkisi = value;
					this.SendPropertyChanged("KullaniciYetkisi");
					this.OnKullaniciYetkisiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Odeme")]
	public partial class Odeme
	{
		
		private string _OdemeTuru;
		
		public Odeme()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTuru", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string OdemeTuru
		{
			get
			{
				return this._OdemeTuru;
			}
			set
			{
				if ((this._OdemeTuru != value))
				{
					this._OdemeTuru = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Satislar")]
	public partial class Satislar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisId;
		
		private string _MusteriNo;
		
		private string _FirmaBilgisi;
		
		private string _UrunKodu;
		
		private string _UrunTanimi;
		
		private int _SatisMiktari;
		
		private decimal _SatisTutari;
		
		private string _OdemeTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisIdChanging(int value);
    partial void OnSatisIdChanged();
    partial void OnMusteriNoChanging(string value);
    partial void OnMusteriNoChanged();
    partial void OnFirmaBilgisiChanging(string value);
    partial void OnFirmaBilgisiChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnUrunTanimiChanging(string value);
    partial void OnUrunTanimiChanged();
    partial void OnSatisMiktariChanging(int value);
    partial void OnSatisMiktariChanged();
    partial void OnSatisTutariChanging(decimal value);
    partial void OnSatisTutariChanged();
    partial void OnOdemeTuruChanging(string value);
    partial void OnOdemeTuruChanged();
    #endregion
		
		public Satislar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatisId
		{
			get
			{
				return this._SatisId;
			}
			set
			{
				if ((this._SatisId != value))
				{
					this.OnSatisIdChanging(value);
					this.SendPropertyChanging();
					this._SatisId = value;
					this.SendPropertyChanged("SatisId");
					this.OnSatisIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriNo", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string MusteriNo
		{
			get
			{
				return this._MusteriNo;
			}
			set
			{
				if ((this._MusteriNo != value))
				{
					this.OnMusteriNoChanging(value);
					this.SendPropertyChanging();
					this._MusteriNo = value;
					this.SendPropertyChanged("MusteriNo");
					this.OnMusteriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaBilgisi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirmaBilgisi
		{
			get
			{
				return this._FirmaBilgisi;
			}
			set
			{
				if ((this._FirmaBilgisi != value))
				{
					this.OnFirmaBilgisiChanging(value);
					this.SendPropertyChanging();
					this._FirmaBilgisi = value;
					this.SendPropertyChanged("FirmaBilgisi");
					this.OnFirmaBilgisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTanimi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UrunTanimi
		{
			get
			{
				return this._UrunTanimi;
			}
			set
			{
				if ((this._UrunTanimi != value))
				{
					this.OnUrunTanimiChanging(value);
					this.SendPropertyChanging();
					this._UrunTanimi = value;
					this.SendPropertyChanged("UrunTanimi");
					this.OnUrunTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisMiktari", DbType="Int NOT NULL")]
		public int SatisMiktari
		{
			get
			{
				return this._SatisMiktari;
			}
			set
			{
				if ((this._SatisMiktari != value))
				{
					this.OnSatisMiktariChanging(value);
					this.SendPropertyChanging();
					this._SatisMiktari = value;
					this.SendPropertyChanged("SatisMiktari");
					this.OnSatisMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisTutari", DbType="Money NOT NULL")]
		public decimal SatisTutari
		{
			get
			{
				return this._SatisTutari;
			}
			set
			{
				if ((this._SatisTutari != value))
				{
					this.OnSatisTutariChanging(value);
					this.SendPropertyChanging();
					this._SatisTutari = value;
					this.SendPropertyChanged("SatisTutari");
					this.OnSatisTutariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTuru", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string OdemeTuru
		{
			get
			{
				return this._OdemeTuru;
			}
			set
			{
				if ((this._OdemeTuru != value))
				{
					this.OnOdemeTuruChanging(value);
					this.SendPropertyChanging();
					this._OdemeTuru = value;
					this.SendPropertyChanged("OdemeTuru");
					this.OnOdemeTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SatislarSil")]
	public partial class SatislarSil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisId;
		
		private string _MusteriNo;
		
		private string _FirmaBilgisi;
		
		private string _UrunKodu;
		
		private string _UrunTanimi;
		
		private int _SatisMiktari;
		
		private decimal _SatisTutari;
		
		private string _OdemeTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisIdChanging(int value);
    partial void OnSatisIdChanged();
    partial void OnMusteriNoChanging(string value);
    partial void OnMusteriNoChanged();
    partial void OnFirmaBilgisiChanging(string value);
    partial void OnFirmaBilgisiChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnUrunTanimiChanging(string value);
    partial void OnUrunTanimiChanged();
    partial void OnSatisMiktariChanging(int value);
    partial void OnSatisMiktariChanged();
    partial void OnSatisTutariChanging(decimal value);
    partial void OnSatisTutariChanged();
    partial void OnOdemeTuruChanging(string value);
    partial void OnOdemeTuruChanged();
    #endregion
		
		public SatislarSil()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatisId
		{
			get
			{
				return this._SatisId;
			}
			set
			{
				if ((this._SatisId != value))
				{
					this.OnSatisIdChanging(value);
					this.SendPropertyChanging();
					this._SatisId = value;
					this.SendPropertyChanged("SatisId");
					this.OnSatisIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriNo", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string MusteriNo
		{
			get
			{
				return this._MusteriNo;
			}
			set
			{
				if ((this._MusteriNo != value))
				{
					this.OnMusteriNoChanging(value);
					this.SendPropertyChanging();
					this._MusteriNo = value;
					this.SendPropertyChanged("MusteriNo");
					this.OnMusteriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaBilgisi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirmaBilgisi
		{
			get
			{
				return this._FirmaBilgisi;
			}
			set
			{
				if ((this._FirmaBilgisi != value))
				{
					this.OnFirmaBilgisiChanging(value);
					this.SendPropertyChanging();
					this._FirmaBilgisi = value;
					this.SendPropertyChanged("FirmaBilgisi");
					this.OnFirmaBilgisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTanimi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UrunTanimi
		{
			get
			{
				return this._UrunTanimi;
			}
			set
			{
				if ((this._UrunTanimi != value))
				{
					this.OnUrunTanimiChanging(value);
					this.SendPropertyChanging();
					this._UrunTanimi = value;
					this.SendPropertyChanged("UrunTanimi");
					this.OnUrunTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisMiktari", DbType="Int NOT NULL")]
		public int SatisMiktari
		{
			get
			{
				return this._SatisMiktari;
			}
			set
			{
				if ((this._SatisMiktari != value))
				{
					this.OnSatisMiktariChanging(value);
					this.SendPropertyChanging();
					this._SatisMiktari = value;
					this.SendPropertyChanged("SatisMiktari");
					this.OnSatisMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisTutari", DbType="Money NOT NULL")]
		public decimal SatisTutari
		{
			get
			{
				return this._SatisTutari;
			}
			set
			{
				if ((this._SatisTutari != value))
				{
					this.OnSatisTutariChanging(value);
					this.SendPropertyChanging();
					this._SatisTutari = value;
					this.SendPropertyChanged("SatisTutari");
					this.OnSatisTutariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTuru", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string OdemeTuru
		{
			get
			{
				return this._OdemeTuru;
			}
			set
			{
				if ((this._OdemeTuru != value))
				{
					this.OnOdemeTuruChanging(value);
					this.SendPropertyChanging();
					this._OdemeTuru = value;
					this.SendPropertyChanged("OdemeTuru");
					this.OnOdemeTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StokHareket")]
	public partial class StokHareket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StokHareketId;
		
		private string _UrunKodu;
		
		private System.DateTime _IslemTarihi;
		
		private int _AlinanMiktar;
		
		private decimal _AlisFiyati;
		
		private decimal _AlisTutari;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStokHareketIdChanging(int value);
    partial void OnStokHareketIdChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnIslemTarihiChanging(System.DateTime value);
    partial void OnIslemTarihiChanged();
    partial void OnAlinanMiktarChanging(int value);
    partial void OnAlinanMiktarChanged();
    partial void OnAlisFiyatiChanging(decimal value);
    partial void OnAlisFiyatiChanged();
    partial void OnAlisTutariChanging(decimal value);
    partial void OnAlisTutariChanged();
    #endregion
		
		public StokHareket()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokHareketId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StokHareketId
		{
			get
			{
				return this._StokHareketId;
			}
			set
			{
				if ((this._StokHareketId != value))
				{
					this.OnStokHareketIdChanging(value);
					this.SendPropertyChanging();
					this._StokHareketId = value;
					this.SendPropertyChanged("StokHareketId");
					this.OnStokHareketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTarihi", DbType="Date NOT NULL")]
		public System.DateTime IslemTarihi
		{
			get
			{
				return this._IslemTarihi;
			}
			set
			{
				if ((this._IslemTarihi != value))
				{
					this.OnIslemTarihiChanging(value);
					this.SendPropertyChanging();
					this._IslemTarihi = value;
					this.SendPropertyChanged("IslemTarihi");
					this.OnIslemTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlinanMiktar", DbType="Int NOT NULL")]
		public int AlinanMiktar
		{
			get
			{
				return this._AlinanMiktar;
			}
			set
			{
				if ((this._AlinanMiktar != value))
				{
					this.OnAlinanMiktarChanging(value);
					this.SendPropertyChanging();
					this._AlinanMiktar = value;
					this.SendPropertyChanged("AlinanMiktar");
					this.OnAlinanMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlisFiyati", DbType="Money NOT NULL")]
		public decimal AlisFiyati
		{
			get
			{
				return this._AlisFiyati;
			}
			set
			{
				if ((this._AlisFiyati != value))
				{
					this.OnAlisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._AlisFiyati = value;
					this.SendPropertyChanged("AlisFiyati");
					this.OnAlisFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlisTutari", DbType="Money NOT NULL")]
		public decimal AlisTutari
		{
			get
			{
				return this._AlisTutari;
			}
			set
			{
				if ((this._AlisTutari != value))
				{
					this.OnAlisTutariChanging(value);
					this.SendPropertyChanging();
					this._AlisTutari = value;
					this.SendPropertyChanged("AlisTutari");
					this.OnAlisTutariChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StokHareketSil")]
	public partial class StokHareketSil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StokHareketId;
		
		private string _UrunKodu;
		
		private System.DateTime _IslemTarihi;
		
		private int _AlinanMiktar;
		
		private decimal _AlisFiyati;
		
		private decimal _AlisTutari;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStokHareketIdChanging(int value);
    partial void OnStokHareketIdChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnIslemTarihiChanging(System.DateTime value);
    partial void OnIslemTarihiChanged();
    partial void OnAlinanMiktarChanging(int value);
    partial void OnAlinanMiktarChanged();
    partial void OnAlisFiyatiChanging(decimal value);
    partial void OnAlisFiyatiChanged();
    partial void OnAlisTutariChanging(decimal value);
    partial void OnAlisTutariChanged();
    #endregion
		
		public StokHareketSil()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokHareketId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StokHareketId
		{
			get
			{
				return this._StokHareketId;
			}
			set
			{
				if ((this._StokHareketId != value))
				{
					this.OnStokHareketIdChanging(value);
					this.SendPropertyChanging();
					this._StokHareketId = value;
					this.SendPropertyChanged("StokHareketId");
					this.OnStokHareketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTarihi", DbType="Date NOT NULL")]
		public System.DateTime IslemTarihi
		{
			get
			{
				return this._IslemTarihi;
			}
			set
			{
				if ((this._IslemTarihi != value))
				{
					this.OnIslemTarihiChanging(value);
					this.SendPropertyChanging();
					this._IslemTarihi = value;
					this.SendPropertyChanged("IslemTarihi");
					this.OnIslemTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlinanMiktar", DbType="Int NOT NULL")]
		public int AlinanMiktar
		{
			get
			{
				return this._AlinanMiktar;
			}
			set
			{
				if ((this._AlinanMiktar != value))
				{
					this.OnAlinanMiktarChanging(value);
					this.SendPropertyChanging();
					this._AlinanMiktar = value;
					this.SendPropertyChanged("AlinanMiktar");
					this.OnAlinanMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlisFiyati", DbType="Money NOT NULL")]
		public decimal AlisFiyati
		{
			get
			{
				return this._AlisFiyati;
			}
			set
			{
				if ((this._AlisFiyati != value))
				{
					this.OnAlisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._AlisFiyati = value;
					this.SendPropertyChanged("AlisFiyati");
					this.OnAlisFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlisTutari", DbType="Money NOT NULL")]
		public decimal AlisTutari
		{
			get
			{
				return this._AlisTutari;
			}
			set
			{
				if ((this._AlisTutari != value))
				{
					this.OnAlisTutariChanging(value);
					this.SendPropertyChanging();
					this._AlisTutari = value;
					this.SendPropertyChanged("AlisTutari");
					this.OnAlisTutariChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urunler")]
	public partial class Urunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UrunId;
		
		private string _UrunKodu;
		
		private string _UrunTanimi;
		
		private int _UrunMiktari;
		
		private decimal _AlisFiyati;
		
		private decimal _SatisFiyati;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIdChanging(int value);
    partial void OnUrunIdChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnUrunTanimiChanging(string value);
    partial void OnUrunTanimiChanged();
    partial void OnUrunMiktariChanging(int value);
    partial void OnUrunMiktariChanged();
    partial void OnAlisFiyatiChanging(decimal value);
    partial void OnAlisFiyatiChanged();
    partial void OnSatisFiyatiChanging(decimal value);
    partial void OnSatisFiyatiChanged();
    #endregion
		
		public Urunler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UrunId
		{
			get
			{
				return this._UrunId;
			}
			set
			{
				if ((this._UrunId != value))
				{
					this.OnUrunIdChanging(value);
					this.SendPropertyChanging();
					this._UrunId = value;
					this.SendPropertyChanged("UrunId");
					this.OnUrunIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTanimi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UrunTanimi
		{
			get
			{
				return this._UrunTanimi;
			}
			set
			{
				if ((this._UrunTanimi != value))
				{
					this.OnUrunTanimiChanging(value);
					this.SendPropertyChanging();
					this._UrunTanimi = value;
					this.SendPropertyChanged("UrunTanimi");
					this.OnUrunTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunMiktari", DbType="Int NOT NULL")]
		public int UrunMiktari
		{
			get
			{
				return this._UrunMiktari;
			}
			set
			{
				if ((this._UrunMiktari != value))
				{
					this.OnUrunMiktariChanging(value);
					this.SendPropertyChanging();
					this._UrunMiktari = value;
					this.SendPropertyChanged("UrunMiktari");
					this.OnUrunMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlisFiyati", DbType="Money NOT NULL")]
		public decimal AlisFiyati
		{
			get
			{
				return this._AlisFiyati;
			}
			set
			{
				if ((this._AlisFiyati != value))
				{
					this.OnAlisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._AlisFiyati = value;
					this.SendPropertyChanged("AlisFiyati");
					this.OnAlisFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisFiyati", DbType="Money NOT NULL")]
		public decimal SatisFiyati
		{
			get
			{
				return this._SatisFiyati;
			}
			set
			{
				if ((this._SatisFiyati != value))
				{
					this.OnSatisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._SatisFiyati = value;
					this.SendPropertyChanged("SatisFiyati");
					this.OnSatisFiyatiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
